examscript/urls.py
from django.contrib import admin
from django.urls import path, include
from exam.views import add_results_view, edit_results_view, delete_results_view, results_pdf_view
from exam.views import add_faculty_view, edit_faculty_view, delete_faculty_view, faculty_pdf_view
from exam.views import add_course_view, edit_course_view, delete_course_view, course_pdf_view
from exam.views import  examoffice_view, exam_to_ar, exam_new_results
from exam.views import add_payments_view, edit_payments_view, delete_payments_view, payments_pdf_view
from exam.views import home_view, complaint_view, complaint_pdf_view, complaint_details_view, track_complaint, complaint_resolved
from exam.views import create_user, ar_view, ar_data_view, exam_data_view, store_view, store_data_view
from exam.views import login_view, sign_up_view, retrieved_script, ar_approved_view, pending_complaints_view
from django.contrib.auth.views import LogoutView, LoginView

from django.views.generic import RedirectView
from exam import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sign_up/', sign_up_view, name="sign_up_page"),
    path("", LoginView.as_view(template_name='registration/login.html'), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),

    path("createuser", create_user, name="create_user_page"),

    path('home/', home_view, name="home_page"),

    path('examoffice/', examoffice_view, name="examoffice_page"),
    path('examdata/<int:complaint_id>/', exam_data_view, name="exam_display_page"),
    path('pendingcomplaints/', pending_complaints_view, name="pending_page"),
    path('examtoar/<int:complaint_id>/', exam_to_ar, name="exam_to_ar_page"),
    path('complaintresolved/<int:complaint_id>/', exam_new_results, name="resolved_page"),
    path('resolved/', complaint_resolved, name="resolved"),

    path('store/', store_view, name="store_page"),
    path('storedata/<int:complaint_id>/', store_data_view, name="store_display_page"),
    path('retrieved/', retrieved_script, name="retrieved_scripts"),

    path('a jax/load-courses/', views.load_courses, name='ajax_load_courses'),
    
    path('faculty/add_faculty/', add_faculty_view, name="add_faculty_page"),
    path('faculty/edit_faculty/<int:faculty_id>/', edit_faculty_view, name="edit_faculty_page"),
    path('delete_faculty/<int:faculty_id>/', delete_faculty_view, name="delete_faculty_page"),
    path('faculty/faculty_pdf/', faculty_pdf_view, name="faculty_pdf_page"),

    path('course/add_course/', add_course_view, name="add_course_page"),
    path('course/edit_course/<int:course_id>/', edit_course_view, name="edit_course_page"),
    path('delete_course/<int:course_id>/', delete_course_view, name="delete_course_page"),
    path('course/course_pdf/', course_pdf_view, name="course_pdf_page"),

    path('complaint/complaint/', complaint_view, name="complaint_page"),
    path('complaint/complaint_pdf/', complaint_pdf_view, name="complaint_pdf_page"),
    path('complaint/edit_complaint/<int:complaint_id>/', complaint_details_view, name="edit_complaint_page"),
    #track complaint
    path('complaint/track', track_complaint, name='tracking'),

    path('ar/', ar_view, name='ar_page'),
    path('ardata/<int:complaint_id>/', ar_data_view, name="ar_display_page"),
    path('arapproved/', ar_approved_view, name='ar_approved_page'),
    path('ajax/load-lecturers/', views.load_lecturers, name='ajax_load_lecturers'),

    path('lecturer/', views.LecturerCreateView.as_view(), name='lecturer_page'),

    path('results/', add_results_view, name='add_results_page'),
    path('results/edit_results/<int:results_id>/', edit_results_view, name="edit_results_page"),
    path('delete_results/<int:results_id>/', delete_results_view, name="delete_results_page"),
    path('exam/results_pdf/', results_pdf_view, name="results_pdf_page"),

    path('payment/', add_payments_view, name='add_payment'),
    path('edit_payment/<int:payment_id>/', edit_payments_view, name="edit_payment"),
    path('delete_payments/<int:payments_id>/', delete_payments_view, name="delete_payment"),
    path('payments_pdf/', payments_pdf_view, name="payments_pdf_page"),
]

exam/models.py
# Create your models here.
from django.db import models
#from django.utils.translation import gettext_lazy as _

from django.contrib.auth.models import AbstractUser, User
# Create your models here.

class User(AbstractUser):
    Registration_Number = models.CharField(max_length=50)
    Custom_username = models.CharField(max_length=30, null=False)
    User_passcode = models.CharField(max_length=30, null=False)
    is_superuser = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    is_examoffice = models.BooleanField(default=False)
    is_ar = models.BooleanField(default=False)  
    is_accounts = models.BooleanField(default=False)
    is_store = models.BooleanField(default=False)
    # Add any additional fields here

class Faculty(models.Model):
    Faculty_Name = models.CharField(max_length=200)
    Faculty_Coordinator = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.Faculty_Name}"
    
class Course(models.Model):
    Faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    Course_Name = models.CharField(max_length=200)
    Course_Duration = models.CharField(max_length=10)
    def __str__(self):
        return f"{self.Course_Name}"


class Complaint(models.Model):    
    type=[("Remark", 'Re-mark'),
        ("Missing_Marks", 'Missing marks'), ]    
    YearOfExam=[("Year_1", 'Year 1'),
        ("Year_2", 'Year 2'),
        ("Year_3", 'Year 3'),
        ("Year_4", 'Year 4'),
        ("Year_5", 'Year 5') ]    
    studymode=[ ("DAY", 'DAY'),
        ("EVENING", 'EVENING'),
        ("WEEKEND", 'WEEKEND')  ]
    study=[ ("Semester", 'Semester'),
        ("Quarter", 'Quarter'),
        ("Term", 'Term'),]
    list=[("Semester_1", '1'),
        ("Semester_2", '2'),
        ("Semester_3", '3'),
        ("Semester_4", '4'),
        ("Semester_5", '5'),]
    status=[("Rejected", 'Rejected'),
        ("Approved", 'Approved'),]
    script=[  ("Not Found", 'Not Found'),
        ("Retrieved", 'Retrieved'),]
    approvals=[ ("Rejected", 'Rejected'),      
        ("Pending", 'Pending'),
        ("Complaint Resolved", 'Complaint Resolved')  ]
    to_registrar =[
        ("Send to Academic Registrar", "Send to Academic Registrar")    ]
    
    Complaint_id = models.IntegerField(primary_key=True)
    track_code = models.CharField(max_length=15, default=False, unique=True)
    Date = models.DateTimeField(verbose_name='Date Submitted', auto_now=True)
    Registration_number = models.CharField(max_length=30)
    Complaint_type = models.CharField(max_length=30, choices=type)
    Paper_Code = models.CharField(max_length=30)
    Paper_Name = models.CharField(max_length=100)
    Year_Of_Exam = models.CharField(max_length=20, choices=YearOfExam)
    Study_System = models.CharField(max_length=30, choices=study)
    Sem_Qter = models.CharField(max_length=30, choices=list)
    Session = models.CharField(max_length=10, choices=studymode, default=False)
    Assigned_Lecturer = models.CharField(max_length=90)
    is_exam_office_approved = models.CharField(max_length=30, choices=approvals)    
    is_store_approved =models.CharField(max_length=30, choices=script)
    to_ar = models.CharField(max_length=30, choices=to_registrar)
    is_ar_approved =models.CharField(max_length=30, choices=status)
    Complaint_resolved = models.CharField(max_length=30, choices=approvals)
    
    
#exam office model
class ExamOffice(models.Model):
    Registration_Number = models.CharField(max_length=100)
    Paper_Code = models.CharField(max_length=20)


class Lecturer(models.Model):
    Name= models.CharField(max_length=150)
    Faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    Course = models.ForeignKey(Course, on_delete=models.CASCADE) 
    def __str__(self):
        return f"{self.Name}"

class AR(models.Model):
    Faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    Course = models.ForeignKey(Course, on_delete=models.CASCADE)
    Lecturer = models.ForeignKey(Lecturer, on_delete=models.CASCADE)


class Results(models.Model):
    YearOfExam=[
        ("2018/2019", "2018/2019"),
        ("2019/2020", "2019/2020"),
        ("2020/2021", "2020/2021"),
        ("2021/2022", "2021/2022"),
        ("2022/2023", '2022/2023'),
        ("2023/2024", "2023/2024")
        ]  
    studymode=[
        ("DAY", 'DAY'),
        ("EVENING", 'EVENING'),
        ("WEEKEND", 'WEEKEND')   
        ]
    study=[
        ("Semester", 'Semester'),
        ("Quarter", 'Quarter'),
        ("Term", 'Term'),
        ]
    list=[
        ("1", '1'),
        ("2", '2'),
        ("3", '3'),
        ("4", '4'),
        ("5", '5'),
    ] 
    Date = models.DateTimeField(verbose_name='Date Submitted', auto_now=True)   
    Registration_Number = models.CharField(max_length=100)
    Faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    Course = models.ForeignKey(Course, on_delete=models.CASCADE)
    Paper_Code = models.CharField(max_length=30)
    Paper_Name = models.CharField(max_length=100)
    Score = models.IntegerField()
    Academic_Year = models.CharField(max_length=20, choices=YearOfExam)
    Study_System = models.CharField(max_length=30, choices=study)
    Sem_Qter = models.CharField(max_length=30, choices=list)
    Session = models.CharField(max_length=10, choices=studymode)
    Script_number = models.IntegerField(null=False)


class Accounts(models.Model):
    YearOfExam=[
        ("Year_1", 'Year 1'),
        ("Year_2", 'Year 2'),
        ("Year_3", 'Year 3'),
        ("Year_4", 'Year 4'),
        ("Year_5", 'Year 5')
        ]  
    studymode=[
        ("DAY", 'DAY'),
        ("EVENING", 'EVENING'),
        ("WEEKEND", 'WEEKEND')   
        ]
    study=[
        ("Semester", 'Semester'),
        ("Quarter", 'Quarter'),
        ("Term", 'Term'),
        ]
    type=[
        ("Remark", 'Re-mark'),
        ("Missing_Marks", 'Missing marks'),
    ]
    list=[
        ("Semester_1", '1'),
        ("Semester_2", '2'),
        ("Semester_3", '3'),
        ("Semester_4", '4'),
        ("Semester_5", '5'),
    ]
    Registration_Number = models.CharField(max_length=100, null=True)
    Faculty = models.CharField(max_length=100, null=True)
    Course = models.CharField(max_length=100, null=True)
    Paper_Code = models.CharField(max_length=30, null=True)
    Paper_Name = models.CharField(max_length=100, null=True)
    Year = models.CharField(max_length=20, choices=YearOfExam, null=True)
    Study_System = models.CharField(max_length=30, choices=study, null=True)
    Sem_Qter = models.CharField(max_length=30, choices=list, null=True)
    Session = models.CharField(max_length=10, choices=studymode, null=True)
    Complaint_type = models.CharField(max_length=10, default="Remark", null=False)
    Amount_Paid = models.IntegerField(null=False)
    Date = models.DateTimeField(verbose_name='Date Submitted', auto_now=True)

exam/forms.py
from django.forms import ModelForm
from .models import Faculty, Course, AR, Lecturer, Complaint, Results, Accounts
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
import random, string

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password')
        

class FacultyForm(ModelForm):
    class Meta:
        model = Faculty
        fields = '__all__'

class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

class ExamofficeForm(forms.Form):
    Registration_number = forms.CharField(required=False)
    Paper_Code = forms.CharField(required=False)


class ExamComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ('Registration_number','Complaint_type','Paper_Code','Paper_Name','Year_Of_Exam', 'Study_System', 'Sem_Qter', 'Session', 'is_exam_office_approved')

class ExamToArForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ('Registration_number','Complaint_type','Paper_Code','Paper_Name','Year_Of_Exam', 'Study_System', 'Sem_Qter', 'Session', 'to_ar')

class ExamComplaintResolvedForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ('Registration_number','Complaint_type','Paper_Code','Paper_Name','Year_Of_Exam', 'Study_System', 'Sem_Qter', 'Session', 'Complaint_resolved')


class StoreComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ('Registration_number','Complaint_type','Paper_Code','Paper_Name','Year_Of_Exam', 'Study_System', 'Sem_Qter', 'Session', 'is_store_approved')



class TrackForm(forms.Form):
    Track_code = forms.CharField(required=False)

class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ('Registration_number','Complaint_type','Paper_Code','Paper_Name','Year_Of_Exam', 'Study_System', 'Sem_Qter', 'Session')

    def generate_track_code(self):
        # Generate a unique track code
        characters = string.ascii_uppercase + string.digits
        code = ''.join(random.choice(characters) for _ in range(10))
        while Complaint.objects.filter(track_code=code).exists():
            code = ''.join(random.choice(characters) for _ in range(10))
        return code

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.track_code = self.generate_track_code()
        instance.status = 'Pending'  # Set initial status
        if commit:
            instance.save()
        return instance
    



class ArComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ('Registration_number','Complaint_type','Paper_Code','Paper_Name','Year_Of_Exam', 'Study_System', 'Sem_Qter', 'Session', 'Assigned_Lecturer', 'is_ar_approved')

class ARForm(forms.ModelForm):
    class Meta:
        model = AR
        fields = ( 'Faculty', 'Course', 'Lecturer')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['Course'].queryset = Course.objects.none()
    
        if 'Faculty' in self.data:
            try:
                faculty_id = int(self.data.get('Faculty'))
                self.fields['course'].queryset = Course.objects.filter(Faculty_id=faculty_id).order_by('Course_Name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Course queryset
        elif self.instance.pk:
            self.fields['Course'].queryset = self.instance.Faculty.course_set.order_by('Course_Name')
   
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['Lecturer'].queryset = Lecturer.objects.none()

        if 'Course' in self.data:
            try:
                course_id = int(self.data.get('Lecturer'))
                self.fields['Lecturer'].queryset = Lecturer.objects.filter(course_id=course_id).order_by('Name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Course queryset
        elif self.instance.pk:
            self.fields['Lecturer'].queryset = self.instance.Course.Lecturer_set.order_by('Name')


class LecturerForm(ModelForm):
    class Meta:
        model = Lecturer
        fields = ('Name', 'Faculty', 'Course')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['Course'].queryset = Course.objects.none()

        if 'Faculty' in self.data:
            try:
                faculty_id = int(self.data.get('Faculty'))
                self.fields['Course'].queryset = Course.objects.filter(Faculty_id=faculty_id).order_by('Course_Name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Course queryset
        elif self.instance.pk:
            self.fields['Course'].queryset = self.instance.Faculty.course_set.order_by('Course_Name')


class ResultsForm(ModelForm):
    class Meta:
        model = Results
        fields = '__all__'

class AccountsForm(ModelForm):
    class Meta:
        model = Accounts
        fields = '__all__'

#users
class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))    
    

exam/templates/exam/ar_approved.html
{% if user.is_superuser or user.is_authenticated %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {{ redirect_to_login_immediately }}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="/static/css/group.css" rel="stylesheet" />
    <title>Retrieved scripts</title>
  </head>
    <body class="student">
        <div class="main">
            <div class="complaint">
                <h1>APPROVED BY ACADEMIC REGISTRAR</h1>
                <table class="table table-striped">
                <thead>
                    <th scope="col">Complaint id</th>
                    <th scope="col">Submission Date</th>
                    <th scope="col">Registration Number</th>
                    <th scope="col">Complaint Type</th>
                    <th scope="col">Paper Code</th>
                    <th scope="col">Paper Name</th>
                    <th scope="col">Year Of Exam</th>
                    <th scope="col">Study System</th>
                    <th scope="col">Semester| Quarter</th>
                    <th scope="col">Session</th>
                </thead>
                <tbody>
                    {% for filtered_complaints in filtered_complaints %}
                        <tr>
                            <th scope="row">{{filtered_complaints.Complaint_id}}</th>
                            <td>{{filtered_complaints.Date}}</td>
                            <td>{{filtered_complaints.Registration_number}}</td>
                            <td>{{filtered_complaints.Complaint_type}}</td>
                            <td>{{filtered_complaints.Paper_Code}}</td>
                            <td>{{filtered_complaints.Paper_Name}}</td>
                            <td>{{filtered_complaints.Year_Of_Exam}}</td>
                            <td>{{filtered_complaints.Study_System}}</td>
                            <td>{{filtered_complaints.Sem_Qter}}</td>
                            <td>{{filtered_complaints.Session}}</td>
                            <td>
                                <a href="{% url 'resolved_page' filtered_complaints.Complaint_id %}">
                                  <button  class="btn btn-success">VIEW DETAILS</button>
                                </a>
                              </td>
                        </tr>
                    {% empty %}
                        <center><h4>No complaints approved at the moment.</h4></center>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </body>
</html>
{% endif %}

exam/templates/exam/ar_complaint_data.html
<!DOCTYPE html>
<html>
<head>
    {% load crispy_forms_tags %}
    <title>ar Data</title>
</head>
<body>
    <h1>Academic Registrar Display Data:</h1>

    <form method="post">
        {% csrf_token %}
        {{form|crispy}}

        <br>
        <button type="submit" class="btn btn-outline-success">APPROVE COMPLAINT</button>
    </form>
</body>
</html>

exam/templates/exam/ar_form.html
{% if user.is_superuser or user.is_ar %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {{ redirect_to_login_immediately }}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% load crispy_forms_tags %}
    <link href="/static/css/group.css" rel="stylesheet" />
    <title>Academic Registra</title>
  </head>
  <body class="student">
    <div class="armain">
      <div class="arcomplaint">
        <h1>COMPLAINTS FOR APPROVAL</h1>
        <table class="table table-striped">
          <thead>
              <th scope="col">Complaint id</th>
              <th scope="col">Complaint Date</th>
              <th scope="col">Registration Number</th>
              <th scope="col">Complaint Type</th>
          </thead>
          <tbody>
            {% for filtered_complaints in filtered_complaints %}
              <tr>
                <th scope="row">{{filtered_complaints.Complaint_id}}</th>
                <td>{{filtered_complaints.Date}}</td>
                <td>{{filtered_complaints.Registration_number}}</td>
                <td>{{filtered_complaints.Complaint_type}}</td>
                <td>
                  <a href="{% url 'ar_display_page' filtered_complaints.Complaint_id %}">
                    <button  class="btn btn-success">VIEW DETAILS</button>
                  </a>
                </td>
                <td>
                  <a href="mailto:fahadmusty@gmail.com?subject=Please go to the Exams Office and attend to this student's exam complaint&body=Complaint ID:  {{filtered_complaints.Complaint_id}}%0D%0AComplaint Date:  {{filtered_complaints.Date}}%0D%0ARegistration Number:  {{filtered_complaints.Registration_number}}%0D%0AComplaint Type:  {{filtered_complaints.Complaint_type}}">
                      <button class="btn btn-outline-primary">SEND EMAIL</button>
                  </a>
              </td>
              </tr>
              {% empty %}
                <center><h4>No objects found.</h4></center>
            {% endfor %}
          </tbody>
      </table>
      </div>
      <div class="arheading">
        <div class="head">
            <h1>ACADEMIC REGISTRAR FORM</h1>
        </div>
        <div class="form-control" id="arForm" data-courses-url="{% url 'ajax_load_courses' %}" data-lecturers-url="{% url 'ajax_load_lecturers' %}" novalidate>
          <form method="POST">
              {% csrf_token %}
              {{form|crispy}}
              <center>
              <div>
                  <button class="btn btn-outline-success">SEND EMAIL</button>
              </div><br><br>
              </center>
          </form>
        </div>
      </div>
    </div>

  {% include 'includes/scripts.html' %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $("#id_Faculty").change(function () {
        var url = $("#arForm").attr("data-courses-url");  // get the url of the `load_courses` view
        var facultyId = $(this).val();  // get the selected faculty ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/ajax/load-courses/)
          data: {
            'faculty': facultyId       // add the faculty id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_courses` view function
            $("#id_Course").html(data);  // replace the contents of the course input with the data that came from the server
          }
        });

      });
    </script>

    <script>
      $("#id_Course").change(function () {
        var url = $("#arForm").attr("data-lecturers-url");  // get the url of the `load_courses` view
        var courseId = $(this).val();  // get the selected faculty ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/ajax/load-courses/)
          data: {
            'course': courseId       // add the faculty id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_courses` view function
            $("#id_Lecturer").html(data);  // replace the contents of the course input with the data that came from the server
          }
        });

      });
    </script>
  </body>
</html>
{% endif %}

exam/templates/exam/complaint_resolved.html
{% if user.is_superuser or user.is_store %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {{ redirect_to_login_immediately }}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="/static/css/group.css" rel="stylesheet" />
    <title>resolved</title>
  </head>
    <body class="student">
        <div class="main">
            <div class="complaint">
                <h1>RESOLVED COMPLAINTS</h1>
                <table class="table table-striped">
                <thead>
                    <th scope="col">Complaint id</th>
                    <th scope="col">Submission Date</th>
                    <th scope="col">Registration Number</th>
                    <th scope="col">Complaint Type</th>
                    <th scope="col">Paper Code</th>
                    <th scope="col">Paper Name</th>
                    <th scope="col">Year Of Exam</th>
                    <th scope="col">Study System</th>
                    <th scope="col">Semester| Quarter</th>
                    <th scope="col">Session</th>
                </thead>
                <tbody>
                    {% for filtered_complaints in filtered_complaints %}
                    <tr>
                        <th scope="row">{{filtered_complaints.Complaint_id}}</th>
                        <td>{{filtered_complaints.Date}}</td>
                        <td>{{filtered_complaints.Registration_number}}</td>
                        <td>{{filtered_complaints.Complaint_type}}</td>
                        <td>{{filtered_complaints.Paper_Code}}</td>
                        <td>{{filtered_complaints.Paper_Name}}</td>
                        <td>{{filtered_complaints.Year_Of_Exam}}</td>
                        <td>{{filtered_complaints.Study_System}}</td>
                        <td>{{filtered_complaints.Sem_Qter}}</td>
                        <td>{{filtered_complaints.Session}}</td>
                    </tr>
                    {% empty %}
                        <center><h4>No Exam scripts retrieved at the moment.</h4></center>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </body>
</html>
{% endif %}

exam/templates/exam/lecturer_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% load crispy_forms_tags %}
    <link href="/static/css/group.css" rel="stylesheet" />
    <title>Lecturer</title>
  </head>
  <body class="student">
    <div class="main">
      <div class="heading">
          <div class="head">
              <h1>Lecturer Registration Form</h1>
          </div>
          <div class="form-control" id="lecturerForm" data-courses-url="{% url 'ajax_load_courses' %}" novalidate>
              <form method="POST">
                  {% csrf_token %}
                  {{form|crispy}}
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <a href="{% url 'home_page' %}">Nevermind</a>
              </form>
          </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $("#id_Faculty").change(function () {
        var url = $("#lecturerForm").attr("data-courses-url");  // get the url of the `load_courses` view
        var facultyId = $(this).val();  // get the selected faculty ID from the HTML input

        $.ajax({                       // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/ajax/load-courses/)
          data: {
            'faculty': facultyId       // add the faculty id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `load_courses` view function
            $("#id_Course").html(data);  // replace the contents of the course input with the data that came from the server
          }
        });

      });
    </script>
  </body>
</html>